# -*- coding: utf-8 -*-
"""Copie de TP_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WgE92uMBrRspPnftieS7KhUAosrokf9

Import data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

DataLong1_URL = 'https://raw.githubusercontent.com/health-data-science-OR/' \
            + 'hpdm139-datasets/main/syn_ts_ed_long.csv'
DataLarge1_URL = 'https://raw.githubusercontent.com/health-data-science-OR/' \
            + 'hpdm139-datasets/main/syn_ts_ed_wide.csv'

long_df = pd.read_csv(DataLong1_URL)
long_df.head()

long_df = pd.read_csv(DataLarge1_URL)
long_df.head()

def ed_data_to_wide(file_path):
    # column name transformation
    translated_names = {0:'hosp_1',
                        1:'hosp_2',
                        2:'hosp_3',
                        3:'hosp_4'}

    data_types = {'hosp_1':np.int64,
                  'hosp_2':np.int64,
                  'hosp_3':np.int64,
                  'hosp_4':np.int64}

    long_df = (pd.read_csv(file_path)
            .pivot_table(values=['attends'], index=['date'], columns=['hosp'])
            .T.reset_index(drop=True)
            .T.rename(columns=translated_names)
            .assign(date=lambda x: pd.to_datetime(x.index))
            .set_index('date')
            .astype(data_types)
         )

    return long_df
large_df = ed_data_to_wide(DataLong1_URL)
large_df.info()

large_df = ed_data_to_wide(DataLong1_URL)
large_df.info()

def ed_data_to_long(file_path):
    translated_names = {'hosp_':'attends'}
    data_types = {'hosp': np.int16, 'attends':np.int64}

    long_df = (
                pd.wide_to_long(pd.read_csv(file_path), stubnames='hosp_',
                                i=['date'], j='hosp')
                .reset_index()
                .rename(columns=translated_names)
                .assign(date=lambda x: pd.to_datetime(x['date']))
                .astype(data_types)
                )

    return long_df

long_df = ed_data_to_long(DataLarge1_URL)
long_df.info()

# example solution

fig = plt.figure(figsize=(12,3))
ax = fig.add_subplot()
ax.set_xlabel("Date", fontsize=12)
ax.set_ylabel("Patients attending emergency", fontsize=12)

_ = ax.plot(large_df['hosp_1'], lw=1)
# include x, y grid
_ = ax.grid(ls='--')

# set size of x, y ticks
_ = ax.tick_params(axis='both', labelsize=12)

# save the figure
fig.savefig('hosp_1_ed.png', dpi=300)

fig, axs = plt.subplots(nrows=4, ncols=1, tight_layout=True, figsize=(12,10),
                        sharex=True)

# note that axis is a 2D array
FS_SUBTITLE = 12
for hosp_idx in range(0,4):
    _ = axs[hosp_idx].plot(large_df[f'hosp_{hosp_idx+1}'])
    _ = axs[hosp_idx].set_title(f'Hospital {hosp_idx+1}', fontsize=FS_SUBTITLE)
    _ = axs[hosp_idx].grid(ls='--')

# axis labels matplotlib
AXIS_LABEL_SIZE = 12
_ = fig.supylabel('Patients attending emergency', fontsize=AXIS_LABEL_SIZE)
_ = fig.supxlabel('Date', fontsize=AXIS_LABEL_SIZE)

hospital_ref_mapping = {1: '230', 2: '240', 3: '250', 4: '260'}
long_df['hospital_ref'] = long_df['hosp'].map(hospital_ref_mapping)

# Afficher les 5 premières lignes pour vérifier
print(long_df)

specific_date = '2014-04-01'
filtered_df = long_df[long_df['date'] == specific_date]

# Agréger les données pour obtenir le nombre de patients pour chaque hôpital à cette date
hospital_attends_sum = filtered_df.groupby('hospital_ref')['attends'].sum()

# Créer un histogramme pour représenter le nombre de patients par hôpital pour la date donnée
fig, ax = plt.subplots(figsize=(8, 6))
ax.bar(hospital_attends_sum.index, hospital_attends_sum.values, color=['blue', 'orange', 'green', 'red'])

# Ajouter des étiquettes et le titre
ax.set_title(f'Nombre de patients par hôpital pour la date {specific_date}', fontsize=16)
ax.set_xlabel('Hôpital', fontsize=14)
ax.set_ylabel('Nombre de patients', fontsize=14)

# Afficher les valeurs sur chaque barre
for i, value in enumerate(hospital_attends_sum.values):
    ax.text(i, value + 0.5, str(value), ha='center', fontsize=12)

plt.show()

